TLSA-12-TLSA-5 Create edit-task jsp and servlet
KaterynaHolt/TODO-list-servlets-api pull request #8
Opened 2023-04-13 22:01 UTC by KaterynaHolt

1. Created edit-task jsp page
2. Created edit-task servlet
3. Implemented logic to open edit-task.jsp page while clicking on Edit link
4. Implemented logic to edit task after clicking on Edit button
5. Implemented logic to complete task after clicking on Complete link
6. Implemented logic to incomplete task after clicking on Incomplete link
7. Implemented logic to remove task after clicking on Remove link
8. Fixed junit tests in the class ToDoStoreSingletoneTest

2023-04-13 22:02 UTC, KaterynaHolt commented
![Screenshot 2023-04-14 at 00-50-15 Edit task](https://user-images.githubusercontent.com/114435467/231892514-6cb315a8-fd1b-4572-b3f3-874e05279807.png)

2023-04-14 20:04 UTC, KaterynaHolt commented
![Screenshot 2023-04-14 at 23-03-36 Edit task](https://user-images.githubusercontent.com/114435467/232144412-56cfea09-8514-48e3-bf77-a068568cd0ee.png)

2023-04-15 15:12 UTC, aholtvianskyi approved these changes

2023-04-15 15:12 UTC, aholtvianskyi commented on src/main/java/com/todolist/app/servlet/EditTaskServlet.java
> +            response.sendRedirect(request.getContextPath() + "/notification?operation=EDIT&id=" + uuid);
`operation=EDIT` might be replaced with `ToDoListAppConstants.EDIT_OPERATION`

2023-04-15 15:12 UTC, aholtvianskyi commented on src/main/java/com/todolist/app/servlet/EditTaskServlet.java
> +        else{
let add a space after `else`

2023-04-15 15:12 UTC, aholtvianskyi commented on src/main/java/com/todolist/app/servlet/EditTaskServlet.java
> +
Lets remove this empty line

2023-04-15 15:12 UTC, aholtvianskyi commented on src/main/java/com/todolist/app/servlet/EditTaskServlet.java
> +        String uuid = (String) session.getAttribute("uuid");
Why we get this attribute from session instead of request?

2023-04-15 15:12 UTC, aholtvianskyi commented on src/main/webapp/jsp/edit-task.jsp
> +        session.setAttribute("uuid", String.valueOf(uuid));%>
You might add this uuid field as an input in the form, but hidden. After that you will be able to send in to servlet in scope of the request, I guess.

2023-04-15 15:17 UTC, aholtvianskyi requested changes

2023-04-15 15:17 UTC, aholtvianskyi commented on src/main/java/com/todolist/app/servlet/EditTaskServlet.java
> +    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
By the way, can we implement a test on this? E.g. https://stackoverflow.com/questions/5434419/how-to-test-my-servlet-using-junit

2023-04-16 17:24 UTC, merged